// Localhost
### Get all contacts
GET http://localhost:8080/customers

### Get contact by ID
GET http://localhost:8080/customers/67413f87227dd0db7e3e9331

// Render
### Get all contacts
GET https://project1-ad3r.onrender.com/customers

### Get contact by ID
GET https://project1-ad3r.onrender.com/customers/67413f87227dd0db7e3e9331

### Create Contact Localhost
POST http://localhost:8080/customers HTTP/1.1
Content-Type: application/json

{
    "firstName": "JoeTest",
    "lastName": "Test",
    "email": "joe.test@test.com",
    "itin": "",
    "businessName": "abcadbdbdbdsdfb",
    "phoneNumber": "1231231231",
    "address": "1 avenida 9-69 zona 2 , Guatemala"
}

### Create Contact Render.com
POST https://project1-ad3r.onrender.com/customers HTTP/1.1
Content-Type: application/json

{
    "firstName": "LocalJoeTest",
    "lastName": "Test",
    "email": "joe.test@test.com",
    "itin": "abceddd",
    "businessName": "1hola",
    "phoneNumber": "54338708",
    "address": "1 avenida 9-69 zona 2 , Guatemala"
}

### Update Contact
PUT http://localhost:8080/customers/67415d6ca042c52e772e907b HTTP/1.1
Content-Type: application/json

{
    "firstName": "RJoeTest",
    "lastName": "RTest",
    "email": "joe.test@test.com",
    "itin": "1235252",
    "businessName": "1hola",
    "phoneNumber": "54338708",
    "address": "1 avenida 9-69 zona 2 , Guatemala"
}

### Update Contact Render.com
PUT https://project1-ad3r.onrender.com/contacts/67413f87227dd0db7e3e9331 HTTP/1.1
Content-Type: application/json

{
    "firstName": "JoeTest",
    "lastName": "Test",
    "email": "joe.test@test.com",
    "itin": "1235252",
    "businessName": "1hola",
    "phoneNumber": "54338708",
    "address": "1 avenida 9-69 zona 2 , Guatemala"
}

### Delete Contact
DELETE http://localhost:8080/customers/67413fb1227dd0db7e3e9333

### Delete Contact Render.com
DELETE https://project1-ad3r.onrender.com/customers/6738a84222c1c7d91589f96a

### ---------------------------Products-------------------------------------

### Get All products
GET http://localhost:8080/products

### Get contact by ID
GET http://localhost:8080/products/6742a68214602cb06478ff23

### Create New Product
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
    "productName": "Clothes",
    "price": "100",
    "description": "T-shirt",
    "quantity": "12",
    "purchaseDate": "12-09",
    "discount": "1",
    "providerId": "1000"
}

### Update Products
PUT http://localhost:8080/products/6742a6413a33d5cca2947fd2 HTTP/1.1
Content-Type: application/json

{
    "productName": "Computer",
    "price": "100",
    "description": "Dell Insipiron 1020",
    "quantity": "12",
    "purchaseDate": "2002-12-09",
    "discount": "5",
    "providerId": "1001"
}
### Delete Producst
DELETE http://localhost:8080/products/6742a6423a33d5cca2947fd4
